name: DinD
on:
  push:
  pull_request:
jobs:
  dind:
    runs-on: ubuntu-latest
    container:
      image: docker:stable-dind
      options: --privileged
      env:
        GITHUB_ACTION: ${GITHUB_ACTION}
        GITHUB_ACTOR: ${GITHUB_ACTOR}
        GITHUB_API_URL: ${GITHUB_API_URL}
        GITHUB_BASE_REF: ${GITHUB_BASE_REF}
        GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}
        GITHUB_EVENT_PATH: ${GITHUB_EVENT_PATH}
        GITHUB_GRAPHQL_URL: ${GITHUB_GRAPHQL_URL}
        GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}
        GITHUB_REF: ${GITHUB_REF}
        GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}
        GITHUB_SERVER_URL: ${GITHUB_SERVER_URL}
        GITHUB_SHA: ${GITHUB_SHA}
        RUNNER_OS: ${RUNNER_OS}
        RUNNER_TEMP: ${RUNNER_TEMP}
        RUNNER_TOOL_CACHE: ${RUNNER_TOOL_CACHE}
        RUNNER_WORKSPACE: ${RUNNER_WORKSPACE}
    steps:
    - name: Run docker info
      run: docker info
    - name: Run Docker container
      run: docker run --rm alpine:3.12 echo Hello, world!
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: node -v
