name: DinD
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Build Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: joschi/docker-in-docker-action-test
        tags: latest
  dind:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: joschi/docker-in-docker-action-test:latest
      options: --privileged
      env:
        GITHUB_ACTION: ${GITHUB_ACTION}
        GITHUB_ACTOR: ${GITHUB_ACTOR}
        GITHUB_API_URL: ${GITHUB_API_URL}
        GITHUB_BASE_REF: ${GITHUB_BASE_REF}
        GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}
        GITHUB_EVENT_PATH: ${GITHUB_EVENT_PATH}
        GITHUB_GRAPHQL_URL: ${GITHUB_GRAPHQL_URL}
        GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}
        GITHUB_REF: ${GITHUB_REF}
        GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}
        GITHUB_SERVER_URL: ${GITHUB_SERVER_URL}
        GITHUB_SHA: ${GITHUB_SHA}
        RUNNER_OS: ${RUNNER_OS}
        RUNNER_TEMP: ${RUNNER_TEMP}
        RUNNER_TOOL_CACHE: ${RUNNER_TOOL_CACHE}
        RUNNER_WORKSPACE: ${RUNNER_WORKSPACE}
    steps:
    - name: Prepare qemu
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - name: Run arm32v6/alpine Docker image
      run: docker run --rm -t arm32v6/alpine uname -m
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: node -v
